mosaicDB/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from search import views as sev
from submit import views as suv


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', sev.home),
    url(r'^submit$',suv.submit),
    url(r'^search$', sev.viewvar, name='detail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls')),
    url(r'^browser/', include('cms_genome_browser.urls', namespace='cms_genome_browser')),
    url(r'var/(?P<varid>[0-9]+)$', sev.varpage),
    url(r'gen/(?P<entrez>[0-9]+)$', sev.genpage),
    url(r'ind/(?P<indid>[0-9]+\.[0-9]+)$', sev.indpage),
    url(r'dis/(?P<omim>[0-9]+)$', sev.dispage),
    url(r'addpage$', sev.addpage),
    url(r'^ajax_list/$', sev.ajax_list, name='ajax-list'),
    url(r'^menu/$', sev.menupage),
    url(r'^menulist$', sev.menu, name='listinfo'),
)

urlpatterns += patterns('', (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from __future__ import unicode_literals

from django.db import models

class Variant(models.Model):
    class Meta:
        managed=False
    varid = models.IntegerField(primary_key=True)
    gene = models.CharField(max_length=30)
    chrom = models.CharField(max_length=5)
    start = models.IntegerField()
    end = models.IntegerField()
    disease = models.CharField(max_length=100)
    method = models.CharField(max_length=50)

class pubinfo(models.Model):
    class Meta:
        managed=False
    pmid = models.IntegerField(primary_key=True,unique=True)
    title = models.CharField(max_length=200)
    journal = models.CharField(max_length=100)
    date = models.CharField(max_length=10)
    disease = models.CharField(max_length=50)
    population = models.CharField(max_length=50, blank=True, default='')
    incidence_lower = models.CharField(max_length=50, blank=True, default='')
    incidence_higher = models.CharField(max_length=50, blank=True, default='')
    male_cases = models.IntegerField(null=True, blank=True)
    female_cases = models.IntegerField(null=True, blank=True)
    other_cases = models.IntegerField(null=True, blank=True)
    paternal_age_effect = models.CharField(max_length=50, blank=True,default='')
 #   note = models.CharField(max_length=500, blank=True)

class indinfo(models.Model):
    class Meta:
        managed=False
    indid = models.CharField(max_length=20,primary_key=True,unique=True)
    pmid = models.IntegerField()
    whose_mosaic = models.CharField(max_length=10)
    patient_mosaic_origin = models.CharField(max_length=10, blank=True,default='')
    phenotype_mosaic = models.IntegerField()
    age_lower = models.FloatField(null=True, blank=True)
    age_upper = models.FloatField(null=True, blank=True)
    affected_child_nc = models.IntegerField(null=True, blank=True)
    affected_male_child_nc = models.IntegerField(null=True, blank=True)
    affected_female_child_nc = models.IntegerField(null=True, blank=True)
    affected_grandson = models.IntegerField(null=True, blank=True)
    affected_granddaughter = models.IntegerField(null=True, blank=True)
    disease = models.CharField(max_length=50)
    omim = models.IntegerField()

class geneinfo(models.Model):
    class Meta:
        managed=False
    entrez = models.IntegerField(primary_key=True,unique=True)
    symbol = models.CharField(max_length=20)
    fullname = models.CharField(max_length=50)
    location = models.CharField(max_length=20)
    other_ids = models.CharField(max_length=100)
    other_names = models.CharField(max_length=100)
    summary = models.CharField(max_length=1000)

class Varinfo(models.Model):
    class Meta:
        managed=False
    varid = models.AutoField(primary_key=True)
    indid = models.ManyToManyField(indinfo)
    entrez = models.ForeignKey(geneinfo)
    pmid = models.ManyToManyField(pubinfo)
    gene = models.CharField(max_length=30)
    chrom = models.CharField(max_length=5)
    start = models.IntegerField()
    end = models.IntegerField()
    dna_ref_nt = models.CharField(max_length=30)
    dna_alt_nt = models.CharField(max_length=30)
    hgvs = models.CharField(max_length=100,unique=True)
    genome_assembly = models.CharField(max_length=10)
    exon_intron = models.CharField(max_length=10)
    exon_number = models.CharField(max_length=10, blank=True, default='')
    exon_nc = models.CharField(max_length=10, blank=True, default='')
    protein_position = models.IntegerField(null=True, blank=True)
    pro_ref_aa = models.CharField(max_length=10, blank=True, default='')
    pro_alt_aa = models.CharField(max_length=10, blank=True, default='')
    frameshift = models.CharField(max_length=10, blank=True, default='')
    aa_indel = models.CharField(max_length=30, blank=True, default='')
    cdna_position = models.CharField(max_length=10, blank=True, default='')
    cdna_ref_aa = models.CharField(max_length=10, blank=True, default='')
    cdna_alt_aa = models.CharField(max_length=10, blank=True, default='')
    nt_indel = models.CharField(max_length=30, blank=True, default='')
    mrna_accession = models.CharField(max_length=30)
    mrna_length = models.IntegerField(null=True)
    ref_length = models.IntegerField(null=True)
    disease = models.CharField(max_length=100, null=True)


class mosaic(models.Model):
    id = models.AutoField(primary_key=True)
    ind = models.ForeignKey(indinfo)
    af_lower = models.FloatField(null=True, blank=True)
    af_upper = models.FloatField(null=True, blank=True)
    total_red = models.IntegerField(null=True, blank=True)
    sample_type = models.CharField(max_length=30)
    method = models.CharField(max_length=30)
    var = models.ForeignKey(Varinfo)
    
class doinfo(models.Model):
    class Meta:
        managed=False
    doid = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    defi = models.CharField(max_length=500)
    omim = models.CharField(max_length=200)
    is_a = models.CharField(max_length=30)

templates/add.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<body>
 
<div id="list">Ajax 加载列表</div>
<p id="list_result"></p>

<div id="list">

 
<script src="{% static 'search/jquery.min.js' %}"></script>
<script>
    $(document).ready(function(){
      $('#list').one( "click", function(){
          $.getJSON('/ajax_list/',{'a':10},function(ret){
            //返回值 ret 在这里是一个列表
            for (var i = ret.length - 1; i >= 0; i--) {
              // 把 ret 的每一项显示在网页上
              $('#list_result').append(' ' + ret[i])
            };
          })
      })
    });
</script>
</body>
</html>

templates/disease.html
{% load staticfiles %}
{% load replace %}
{% include 'header.html' %}
   <script src="{% static 'search/sorttable.js' %}"></script>
   <link href="{% static 'search/my.css' %}" rel="stylesheet">
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>
<body>

{% include 'navi.html' %}
<div class='tabs'>
<h1> {% replace search="_" replacement=" " %}{{ disease }}{% endreplace %} (OMIM ID: {{ omim }})</h1>
    <p>Found {{ variants|length }} variant{{ variants|pluralize }} in this database.</p>
    <ul>
    <table class="sortable bordered search" id="table" >
        <tr>
            <th>Variant ID</th>
            <th>Entrez Gene ID</th>
            <th>Gene</th>
            <th>Chromsome</th>
            <th>Start</th>
            <th>End</th>
            <th>Disease</th>
            <th>Method</th>
        </tr>
        {% for variant in variants %}
        <tr>
            <td><a href='/var/{{ variant.varid }}'> {{ variant.varid }}</a></td>
            <td><a href='/gen/{{ variant.entrez.entrez }}'>{{ variant.entrez.entrez }}</a></td>
            <td>{{ variant.gene }}</td>
            <td>{{ variant.chrom }}</td>
            <td>{{ variant.start }}</td>
            <td>{{ variant.end }}</td>
            <td>
            {% regroup variant.indid.all by disease as disease_list %}           
            {% for disease in disease_list %}
                <a href='/dis/{{ disease.list.0.omim }}'>{% replace search="_" replacement=" " %}{{ disease.grouper }}{% endreplace %}</a>
            {% endfor %}
            </td>
            <td>
            {% regroup variant.mosaic_set.all by method as method_list %}
            {% for method in method_list %}
                {{ method.grouper }}
            {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
    </ul>
</div>

</body>
{% include 'footer.html' %}

templates/gene.html
{% load staticfiles %}
{% load replace %}
{% include 'header.html' %}
   <script src="{% static 'search/sorttable.js' %}"></script>
   <link href="{% static 'search/my.css' %}" rel="stylesheet">
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>
<body>

{% include 'navi.html' %}
<div class='tabs'>
<h1> {{ gene.symbol }} (Entrez ID: {{ gene.entrez }})</h1>
    <table class="bordered">
        <tr>
            <th>Entrez Gene ID</th>
            <td><a href="http://www.ncbi.nlm.nih.gov/gene?term={{ gene.entrez }}">{{ gene.entrez }}</a></td>
        </tr>
        <tr>
            <th>Official Gene Symbol</th>
            <td>{{ gene.symbol }}</td>
        </tr>
        <tr>
            <th>Full name</th>
            <td>{{ gene.fullname }}</td>
        </tr>
        <tr>
            <th>Location</th>
            <td>{{ gene.location }}</td>
        </tr>
        <tr>
            <th>Other ids</th>
            <td>
            {% for db, id in dblinks.items %}
            {{ db }} : <a href={{ id.1 }} target="_blank">{{ id.0 }}</a></br>
            {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Other names</th>
            <td>
                {% for name in names %}
                    {% if forloop.last %}
                        {{ name }}
                    {% else %}
                        {{ name }},
                    {% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Summary</th>
            <td>{{ gene.summary }}</td>
        </tr>
    </table>
</div>
<div class="tab2">
<h1>Variants</h1>
    <p>Found {{ variants|length }} variant{{ variants|pluralize }} in this database.</p>
    <table class="sortable bordered search" id="table" >
        <tr>
            <th>Variant ID</th>
            <th>Entrez Gene ID</th>
            <th>Gene</th>
            <th>Chromsome</th>
            <th>Start</th>
            <th>End</th>
            <th>Disease</th>
            <th>Method</th>
        </tr>
        {% for variant in variants %}
        <tr>
            <td><a href='/var/{{ variant.varid }}'> {{ variant.varid }}</a></td>
            <td><a href='/gen/{{ variant.entrez.entrez }}'>{{ variant.entrez.entrez }}</a></td>
            <td>{{ variant.gene }}</td>
            <td>{{ variant.chrom }}</td>
            <td>{{ variant.start }}</td>
            <td>{{ variant.end }}</td>
            <td>
            {% regroup variant.indid.all by disease as disease_list %}           
            {% for disease in disease_list %}
                <a href='/dis/{{ disease.list.0.omim }}'>{% replace search="_" replacement=" " %}{{ disease.grouper }}{% endreplace %}</a>
            {% endfor %}
            </td>
            <td>
            {% regroup variant.mosaic_set.all by method as method_list %}
            {% for method in method_list %}
                {{ method.grouper }}
            {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

</body>
{% include 'footer.html' %}

templates/individual.html
{% load staticfiles %}
{% load replace %}
{% include 'header.html' %}
   <script src="{% static 'search/sorttable.js' %}"></script>
   <link href="{% static 'search/my.css' %}" rel="stylesheet">
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>
<body>

{% include 'navi.html' %}
<div class='tabs'>
<h1> Individual ID: {{ ind.indid }} </h1>
    <table class=bordered >
        <tr>
            <th>Individual ID</th>
            <td>{{ ind.indid }}</td>
        </tr>
        <tr>
            <th>Pubmed ID</th>
            <td><a href="www.ncbi.nlm.nih.gov/pubmed/{{ ind.pmid }}" target="_blank">{{ ind.pmid }}</td>
        </tr>
        <tr>
            <th>Whose mosaic mutation</th>
            <td>{{ ind.whose_mosaic }}</td>
        </tr>
        <tr>
            <th>Origin of mosaic mutation in patients</th>
            <td>{{ ind.patient_mosaic_origin }}</td>
        </tr>
        <tr>
            <th>Phenotype Mosaic</th>
            <td>{{ ind.phenotype_mosaic }}</td>
        </tr>
        <tr>
            <th>Age lower</th>
            <td>{{ ind.age_lower }}</td>
        </tr>
        <tr>
            <th>Age upper</th>
            <td>{{ ind.age_upper }}</td>
        </tr>
        <tr>
            <th>Number of affected children</th>
            <td>{{ ind.affected_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected male children</th>
            <td>{{ ind.affected_male_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected female children</th>
            <td>{{ ind.affected_female_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected grandson</th>
            <td>{{ ind.affected_grandson }}</td>
        </tr>
        <tr>
            <th>Number of affected granddaughter</th>
            <td>{{ ind.affected_granddaughter }}</td>
        </tr>
        <tr>
            <th>Disease</th>
            <td>{% replace search="_" replacement=" " %}{{ ind.disease }}{% endreplace %}</td>
        </tr>
        <tr>
            <th>OMIM ID</th>
            <td><a href="http://www.omim.org/entry/{{ ind.omim }}" target="_blank">{{ ind.omim }}</td>
        </tr>
    </table> 
</div>
<div class="tab2">
    <h1>Variants</h1>
    <p>Found {{ variants|length }} variant{{ variants|pluralize }} in this database.</p>
    <ul>
    <table class="sortable bordered search" id="table" >
        <tr>
            <th>Variant ID</th>
            <th>Entrez Gene ID</th>
            <th>Gene</th>
            <th>Chromsome</th>
            <th>Start</th>
            <th>End</th>
            <th>Disease</th>
            <th>Method</th>
        </tr>
        {% for variant in variants %}
        <tr>
            <td><a href='/var/{{ variant.varid }}'> {{ variant.varid }}</a></td>
            <td>{{ variant.entrez.entrez }}
            <td>{{ variant.gene }}</td>
            <td>{{ variant.chrom }}</td>
            <td>{{ variant.start }}</td>
            <td>{{ variant.end }}</td>
            <td>{% replace search="_" replacement=" " %}{{ variant.disease }}{% endreplace %}</td>
            <td>{{ variant.method }}</td>
        </tr>
        {% endfor %}
    </table>
    </ul>
</div>

</body>
{% include 'footer.html' %}

templates/template_1.html
{% extends "base.html" %}
{% load cms_tags %}

{% block base_content %}
  {% placeholder template_1_content %}
{% endblock %}

templates/template_2.html
{% extends "base.html" %}
{% load cms_tags %}

{% block base_content %}
  {% placeholder template_2_content %}
{% endblock %}

templates/variant.html
{% load staticfiles %}
{% load replace %}
{% include 'header.html' %}

   <link href="{% static 'search/my.css' %}" rel="stylesheet">
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
</head>
<body>
<script type="text/javascript">
    (function($) {
        $(function() {
            $("#accordion > div").accordion({ header: "h3", collapsible: true });
        })
    })(jQuery);
</script>

{% include 'navi.html' %}

<div class='tabs tabvar'>

<ul id="myTab" class="nav nav-tabs">
   <li class="active">
      <a href="#var" data-toggle="tab">
         Variant Overview
      </a>
   </li>
   <li><a href="#gene" data-toggle="tab">Gene information</a></li>
   <li><a href="#ind" data-toggle="tab">Individual information</a></li>
   <li>
      <a href="#pub" data-toggle="tab">Publication information
      </a>
   </li>
</ul>
<div id="myTabContent" class="tab-content">
   <div class="tab-pane fade in active" id="var">
    <div id="accordion">
    <div>
        <h3><a href="#">Overview</a></h3>
    <table class=bordered>
        <tr>
            <th>Variant ID</th>
            <td>{{ variant.varid }}</td>
        </tr>
        <tr>
            <th>Entrez Gene ID</th>
            <td><a href='/gen/{{ variant.entrez.entrez }}'>{{ variant.entrez.entrez }}</a></td>
        </tr>
        <tr>
            <th>Gene</th>
            <td>{{ variant.gene }}</td>
        </tr>
        <tr>
            <th>Location</th>
            <td>{{ variant.chrom }}:{{ variant.start }}-{{ variant.end }}</td>
        </tr>
        <tr>
            <th>Disease</th>
            <td>
            {% regroup variant.indid.all by disease as disease_list %}
            {% for disease in disease_list %}
            {% replace search="_" replacement=" " %}{{ disease.grouper }}{% endreplace %}<a href='/dis/{{ disease.list.0.omim }}'>(view all the variants in this disease)</a>
            {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Method</th>
            <td>
            {% for ind in variant.indid.all %}
                {% for mosaic in ind.mosaic_set.all %}
                    {{ mosaic.method }}</br>
                {% endfor %}
            {% endfor %}
            </td>
        </tr>
        <tr>
            <th>DNA Reference allele</th>
            <td>{{ variant.dna_ref_nt }}</td>
        </tr>
        <tr>
            <th>DNA Alternative allele</th>
            <td>{{ variant.dna_alt_nt }}</td>
        </tr>
        <tr>
            <th>HGVS format</th>
            <td>{{ variant.hgvs }}</td>
        </tr>
        <tr>
            <th>Genome Assembly</th>
            <td>{{ variant.genome_assembly }}</td>
        </tr>
     </table>
     </div>
     <div>
        <h3><a href="#">Other information</a></h3>
    <table class=bordered>

        <tr>
            <th>Exon or Intron</th>
            <td>{{ variant.exon_intron }}</td>
        </tr>
        <tr>
            <th>Exon number</th>
            <td>{{ variant.exon_number }}</td>
        </tr>
        <tr>
            <th>Exon nc</th>
            <td>{{ variant.exon_nc }}</td>
        </tr>
        <tr>
            <th>Position in protein</th>
            <td>{{ variant.protein_position }}</td>
        </tr>
        <tr>
            <th>Protein reference amino acid</th>
            <td>{{ variant.pro_ref_aa }}</td>
        </tr>
        <tr>
            <th>Protein alternative amino acid</th>
            <td>{{ variant.pro_alt_aa }}</td>
        </tr>
        <tr>
            <th>Frameshift</th>
            <td>{{ variant.frameshift }}</td>
        </tr>
        <tr>
            <th>Amino acid indel</th>
            <td>{{ variant.aa_indel }}</td>
        </tr>
        <tr>
            <th>Position in cDNA</th>
            <td>{{ variant.cdna_position }}</td>
        </tr>
        <tr>
            <th>cDNA reference allele</th>
            <td>{{ variant.cdna_ref_aa }}</td>
        </tr>
        <tr>
            <th>cDNA alternative allele</th>
            <td>{{ variant.cdna_alt_aa }}</td>
        </tr>
        <tr>
            <th>Indel</th>
            <td>{{ variant.nt_indel }}</td>
        </tr>
        <tr>
            <th>mRNA accession</th>
            <td>{{ variant.mrna_accession }}</td>
        </tr>
        <tr>
            <th>mRNA length</th>
            <td>{{ variant.mrna_length }}</td>
        </tr>
        <tr>
            <th>Reference length</th>
            <td>{{ variant.ref_length }}</td>
        </tr>
        <tr>
            <th>CI of allele frequency (lower)</th>
            <td>{{ variant.af_lower }}</td>
        </tr>
        <tr>
            <th>CI of allele frequency (upper)</th>
            <td>{{ variant.af_upper }}</td>
        </tr>
        <tr>
            <th>Total read</th>
            <td>{{ variant.total_red }}</td>
        </tr>
        <tr>
            <th>Sample Type</th>
            <td>{{ variant.sample_type }}</td>
        </tr>
   </table>
   </div>
   </div>
   </div>
   <div class="tab-pane fade" id="gene">
    <table class=bordered>
        <tr>
            <th>Entrez Gene ID</th>
            <td><a href="http://www.ncbi.nlm.nih.gov/gene?term={{ variant.entrez.entrez }}">{{ variant.entrez.entrez }}(NCBI Gene)</a></td>
        </tr>
        <tr>
            <th>Official Gene Symbol</th>
            <td>{{ variant.entrez.symbol }}</td>
        </tr>
        <tr>
            <th>Number of variants in {{ variant.entrez.symbol }} in this database</th>
            <td>{{ genecount}}  <a href="/gen/{{ variant.entrez.entrez }}">(view all the variants)</a></td>
        </tr>
        <tr>
            <th>Full name</th>
            <td>{{ variant.entrez.fullname }}</td>
        </tr>
        <tr>
            <th>Band</th>
            <td>{{ variant.entrez.location }}</td>
        </tr>
        <tr>
            <th>Other ids</th>
            <td>
            {% for db, id in dblinks.items %}
            {{ db }} : <a href={{ id.1 }} target="_blank">{{ id.0 }}</a></br>
            {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Other names</th>
            <td>
                {% for name in names %}
                    {% if forloop.last %}
                        {{ name }}
                    {% else %}
                        {{ name }},
                    {% endif %}
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Summary</th>
            <td>{{ variant.entrez.summary }}</td>
        </tr>
    </table>
   </div>
   <div class="tab-pane fade" id="ind">
	<div id="accordion">
    {% for indid in variant.indid.all %}
    <div>
        <h3><a href="#">Individual #{{ forloop.counter }}</a></h3>
    <table class=bordered>
        <tr>
            <th>Individual ID</th>
            <td>{{ indid.indid }} <a href='/ind/{{ variant.indid.indid }}'>(view all the variants in this individual)</a></td>
        </tr>
        <tr>
            <th>Pubmed ID</th>
            <td><a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ variant.indid.pmid }}" target="_blank">{{ indid.pmid }}</a></td>
        </tr>
        <tr>
            <th>Whose mosaic mutation</th>
            <td>{{ indid.whose_mosaic }}</td>
        </tr>
        <tr>
            <th>Origin of mosaic mutation in patients</th>
            <td>{{ indid.patient_mosaic_origin }}</td>
        </tr>
        <tr>
            <th>Phenotype Mosaic</th>
            <td>{{ indid.phenotype_mosaic }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>
            {% if age_lower %}
            {{ indid.age_lower }} 
            {% if age_upper %}
            ~ {{ indid.age_upper }}
            {% endif %}
            {% else %}
                None
            {% endif %}
            </td>
        </tr>
        <tr>
            <th>Number of affected children</th>
            <td>{{ indid.affected_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected male children</th>
            <td>{{ indid.affected_male_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected female children</th>
            <td>{{ indid.affected_female_child_nc }}</td>
        </tr>
        <tr>
            <th>Number of affected grandson</th>
            <td>{{ indid.affected_grandson }}</td>
        </tr>
        <tr>
            <th>Number of affected granddaughter</th>
            <td>{{ indid.affected_granddaughter }}</td>
        </tr>
        <tr>
            <th>Disease</th>
            <td>{% replace search="_" replacement=" " %}{{ indid.disease }}{% endreplace %}<a href='/dis/{{ indid.omim }}'>(view all the variants in this disease)</a></td>
        </tr>
        <tr>
            <th>OMIM ID</th>
            <td><a href="http://www.omim.org/entry/{{ variant.indid.omim }}" target="_blank">{{ indid.omim }}</a></td>
        </tr>
    </table> 
   </div>
    {% endfor %}
   </div>
   </div>
   <div class="tab-pane fade" id="pub">
	<div id="accordion">
    {% for pmid in variant.pmid.all %}
    <div>
        <h3><a href="#">Publication #{{ forloop.counter }}: {{ pmid.pmid }}</a></h3>
    <table class=bordered>
        <tr>
            <th>Pubmed ID</th>
            <td><a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ pmid.pmid }}" target="_blank">{{ pmid.pmid }}</a></td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ pmid.title }}</td>
        </tr>
        <tr>
            <th>Journal</th>
            <td>{% replace search="_" replacement=" " %}{{ pmid.journal }}{% endreplace %}</td>
        </tr>
        <tr>
            <th>Publication date</th>
            <td>{{ pmid.date }}</td>
        </tr>
        <tr>
            <th>Disease</th>
            <td>{% replace search="_" replacement=" " %}{{ pmid.disease }}{% endreplace %}</td>
        </tr>
        <tr>
            <th>Population</th>
            <td>{{ pmid.population }}</td>
        </tr>
        <tr>
            <th>Incidence</th>
            <td>
            {% if incidence_lower %}
            {{ pmid.incidence_lower }} 
            {% if incidence_upper %}
            ~ {{ pmid.incidence_upper }}
            {% endif %}
            {% else %}
                None
            {% endif %}
            </td>
        </tr>
        <tr>
            <th>Number of male cases</th>
            <td>{{ pmid.male_cases }}</td>
        </tr>
        <tr>
            <th>Number of female cases</th>
            <td>{{ pmid.female_cases }}</td>
        </tr>
        <tr>
            <th>Number of other cases</th>
            <td>{{ pmid.other_cases }}</td>
        </tr>
        <tr>
            <th>Paternal age effect</th>
            <td>{{ paternal_age_effect }}</td>
        </tr>
    </table>
   </div>
   {% endfor %}
   </div>
   </div>
</div>

</div>

</body>
{% include 'footer.html' %}