cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/urls.py
from django.conf.urls import patterns, url
from cms_genome_browser.views import BrowserListView, BrowserDetailView

urlpatterns = patterns('',
    url(r'^$', BrowserListView.as_view(), name='browser_list'),
    url(r'^(?P<slug>[^/]+)$', BrowserDetailView.as_view(), name='browser_detail'),
)

cms_genome_browser/urls.py
from django.conf.urls import patterns, url
from cms_genome_browser.views import BrowserListView, BrowserDetailView, test

urlpatterns = patterns('',
    url(r'^$', BrowserListView.as_view(), name='browser_list'),
#    url(r'test', test),
    url(r'^(?P<slug>[^/]+)$', BrowserDetailView.as_view(), name='browser_detail'),
)

mosaicDB/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from search import views as sev
from submit import views as suv


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', sev.home),
    url(r'^submit$',suv.submit),
    url(r'^search$', sev.viewvar, name='detail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls')),
    url(r'^browser/', include('cms_genome_browser.urls', namespace='cms_genome_browser')),
    url(r'var/(?P<varid>[0-9]+)$', sev.varpage),
    url(r'gen/(?P<entrez>[0-9]+)$', sev.genpage),
    url(r'ind/(?P<indid>[0-9]+\.[0-9]+)$', sev.indpage),
    url(r'dis/(?P<omim>[0-9]+)$', sev.dispage),
    url(r'addpage$', sev.addpage),
    url(r'^ajax_list/$', sev.ajax_list, name='ajax-list'),
    url(r'^menu/$', sev.menupage),
    url(r'^menulist$', sev.menu, name='listinfo'),
)

urlpatterns += patterns('', (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, RegexValidator
from filer.fields.file import FilerFileField
from filer.fields.image import FilerImageField

class Browser(models.Model):

    class Meta:
        ordering = ['name']
        verbose_name = "Genome Browser"
        verbose_name_plural = "Genome Browsers"

    name = models.CharField('browser name',
        help_text='Enter a brief, descriptive name for the browser.',
        max_length=255,
        unique=True,
    )

    description = models.TextField('browser description',
        blank=True,
        help_text='Enter a description for the browser.',
    )

    image = FilerImageField(
        blank=True,
        null=True,
        help_text='Upload/select an image to represent this genome browser.',
        related_name='%(app_label)s_%(class)s_browser_image',
    )

    slug = models.SlugField('slug',
        help_text='Enter a unique slug for this genome browser. ' \
                  'This should get auto-generated.',
        max_length=255,
        unique=True,
    )

    chr = models.CharField('default chromosome',
        help_text='The chromosome to display when the browser loads.',
        max_length=64,
    )

    start = models.IntegerField('default start position',
        help_text='The start position of range to display when the browser loads.',
        validators=[
            MinValueValidator(1),
        ],
    )

    end = models.IntegerField('default end position',
        help_text='The end position of range to display when the browser loads.',
        validators=[
            MinValueValidator(1),
        ],
    )

    coordinate_system = models.ForeignKey('cms_genome_browser.CoordSystem',
        help_text='Select a coordinate system. Taxonomy ID, authority, version, ' \
                  'and UCSC name are shown in parentheses, if present.',
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def clean(self):
        if self.start > self.end:
            raise ValidationError('Start position cannot come after end position.')

    def __str__(self):
        return self.name


class CoordSystem(models.Model):

    class Meta:
        ordering = ['species', 'auth', 'version']
        verbose_name = "Coordinate System"
        verbose_name_plural = "Coordinate Systems"

    UCSC_OLD_REGEX = r'^[a-z]{2}\d+$'                 # gs#
    UCSC_NEW_REGEX = r'^[a-z]{3}[A-Z][a-z]{2}\d+$'    # gggSss#

    species = models.ForeignKey('cms_genome_browser.Species',
        help_text='Select a species. Taxonomy ID is shown in parentheses, if present.',
    )

    auth = models.CharField('authority',
        blank=True,
        help_text='Authority string used in the ' \
                  '<a href="http://dasregistry.org/" target="_blank">DAS Registry</a>.',
        max_length=10,
    )

    version = models.CharField('version',
        blank=True,
        help_text='Version string used in the ' \
                  '<a href="http://dasregistry.org/" target="_blank">DAS Registry</a>.',
        max_length=10,
    )

    ucsc_name = models.CharField('UCSC name',
        blank=True,
        help_text='UCSC genome browser name of the assembly, if defined in the list of ' \
                  '<a href="https://genome.ucsc.edu/FAQ/FAQreleases.html#release1" target="_blank">' \
                  'UCSC genome releases</a>.',
        max_length=10,
        validators=[
            RegexValidator(
                regex='%s|%s' % (UCSC_OLD_REGEX, UCSC_NEW_REGEX),
                message="UCSC name must be of the format 'gs#' or 'gggSss#'.",
                code='invalid_UCSC_name'
            ),
        ]
    )

    def __str__(self):
        coord_system_str = self.species.name
        supplemental = []

        if self.species.taxid:
            supplemental.append(str(self.species.taxid))

        supplemental.append(' '.join([self.auth, self.version]))

        if self.ucsc_name:
            supplemental.append(self.ucsc_name)

        if supplemental:
            coord_system_str += ' (%s)' % '; '.join(supplemental)
        return coord_system_str


class Species(models.Model):

    class Meta:
        ordering = ['name', 'taxid']
        verbose_name = "Species"
        verbose_name_plural = "Species"

    name = models.CharField('species name',
        help_text='Enter the species name.',
        max_length=255,
    )

    taxid = models.IntegerField('taxonomy ID',
        blank=True,
        null=True,
        help_text='Enter the Taxonomy ID for the species. ' \
                  'Taxonomy names and IDs can be found at ' \
                  '<a href="http://www.ncbi.nlm.nih.gov/taxonomy" target="_blank">NCBI</a>.',
    )

    def __str__(self):
        species_str = self.name
        if self.taxid:
            species_str += ' (%s)' % self.taxid
        return species_str


class Stylesheet(models.Model):

    class Meta:
        ordering = ['name',]
        verbose_name='Stylesheet'
        verbose_name_plural='Stylesheets'

    STYLESHEET_TYPE_CHOICES = (
        ('XML', 'DAS XML Stylesheet'),
        ('JSON', 'JSON-encoded Stylesheet'),
    )

    name = models.CharField('stylesheet name',
        help_text='Enter a brief, descriptive name for this stylesheet.',
        max_length=255,
        unique=True,
    )

    description = models.TextField('stylesheet description',
        blank=True,
        help_text='Describe the style this stylesheet provides.',
    )

    style_file = FilerFileField(
        help_text='Upload/select an image to represent this genome browser.select a stylesheet for the track. More info can be found in the ' \
                  '<a href="https://www.biodalliance.org/stylesheets.html" target="_blank">' \
                  'Stylesheets for Dalliance</a> documentation.',
        related_name='%(app_label)s_%(class)s_stylesheet',
    )

    is_downloadable = models.BooleanField('stylesheet downloadable?',
        default=True,
        help_text="Add download button for stylesheet file to the genome browser's info window.",
    )

    style_type = models.CharField('stylesheet type',
        choices=STYLESHEET_TYPE_CHOICES,
        help_text='Select the type of stylesheet being used.',
        max_length=4,
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Track(models.Model):

    class Meta:
        ordering = ['browser', 'order']
        verbose_name = 'Track'
        verbose_name_plural = 'Tracks'

    TRACK_TYPE_CHOICES = (
        ('BAM', 'BAM'),
        ('BED', (
                ('BED-MemStore', 'BED (MemStore)'),
                ('BED-Tabix', 'BED (Tabix)'),
            )
        ),
        ('bigWig', 'bigWig'),
        ('bigBed', 'bigBed'),
        ('DAS', (
                ('DAS-feature', 'DAS (feature)'),
                ('DAS-sequence', 'DAS (sequence)'),
            )
        ),
        ('twoBit', 'twoBit'),
        ('VCF', (
                ('VCF-MemStore', 'VCF (MemStore)'),
                ('VCF-Tabix', 'VCF (Tabix)'),
            )
        ),
        ('WIG', 'WIG'),
    )

    order = models.PositiveIntegerField()

    name = models.CharField('track name',
        help_text='Enter a brief name for the track.',
        max_length=64,
    )

    description = models.CharField('track description',
        blank=True,
        help_text='Enter a short description for the track.',
        max_length=255,
    )

    browser = models.ForeignKey(Browser,
        blank=True,
        null=True,
        help_text='Specify genome browser this track belongs to.',
    )

    track_type = models.CharField('track type',
        choices = TRACK_TYPE_CHOICES,
        help_text='Select the source type for this track.',
        max_length=20,
    )

    data_file = FilerFileField(
        help_text='Upload/select a data file for the track. More info can be found in the ' \
                  '<a href="http://www.biodalliance.org/config-source.html" target="_blank">' \
                  'Configuring a source</a> documentation.',
        related_name='%(app_label)s_%(class)s_data',
    )

    index_file = FilerFileField(
        blank=True,
        null=True,
        help_text="<strong>If data file is a BAM or Tabix file</strong>, upload/select " \
                  "an index file (.bai or .tbi) that corresponds to the track's BAM/Tabix file.",
        related_name='%(app_label)s_%(class)s_index',
    )

    collapse_super_groups = models.BooleanField('CSG?',
        default=False,
        help_text="Attempt to allow more 'gene-like' rendering for some data sources.",
    )

    provides_entrypoint = models.BooleanField('entry?',
        default=False,
        # What are Entry Points? http://genboree.org/theCommons/ezfaq/show/epigenome-workshop?faq_id=467
        help_text='Does this track provide entry points? ' \
                  'Entry points comprise the coordinate system on which annotations are made.',
    )

    pinned = models.BooleanField('pin?',
        default=False,
        help_text="'Pin' this trackc in the non-scrolling section at the top of the browser.",
    )

    is_downloadable = models.BooleanField('D/L?',
        default=True,
        help_text="Add download button for data file to the genome browser's info window.",
    )

    stylesheet = models.ForeignKey('cms_genome_browser.Stylesheet',
        blank=True,
        null=True,
        help_text='Choose a stylesheet to add cusom styles to this track.',
    )

    publish_track = models.BooleanField('publish?',
        default=True,
        help_text='Display track in the genome browser.'
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def payload(self):
        PAYLOADS = {
            'BAM':          '',

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView
from cms_genome_browser.models import Browser

class BrowserListView(ListView):
    model = Browser
    template_name = 'cms_genome_browser/browser_list.html'
    context_object_name = 'browser_list'

    def render_to_response(self, context, **response_kwargs):
        # Shim to affect the CMS Toolbar only
        if self.request.toolbar:

            menu = self.request.toolbar.get_or_create_menu('genome-browsers-menu', 'Genome Browsers')

            url_change = reverse('admin:cms_genome_browser_browser_changelist')
            url_addnew = reverse('admin:cms_genome_browser_browser_add')
            menu.add_sideframe_item('Edit Genome Browsers', url=url_change)
            menu.add_modal_item('Add New Genome Browser', url=url_addnew)
            menu.add_break()

            url_change = reverse('admin:cms_genome_browser_track_changelist')
            url_addnew = reverse('admin:cms_genome_browser_track_add')
            menu.add_sideframe_item('Edit Tracks', url=url_change)
            menu.add_modal_item('Add New Track', url=url_addnew)
            menu.add_break()

            url_change = reverse('admin:cms_genome_browser_stylesheet_changelist')
            url_addnew = reverse('admin:cms_genome_browser_stylesheet_add')
            menu.add_sideframe_item('Edit Stylesheets', url=url_change)
            menu.add_modal_item('Add New Stylesheet', url=url_addnew)
            menu.add_break()

            url_change = reverse('admin:cms_genome_browser_species_changelist')
            url_addnew = reverse('admin:cms_genome_browser_species_add')
            menu.add_sideframe_item('Edit Species', url=url_change)
            menu.add_modal_item('Add New Species', url=url_addnew)
            menu.add_break()

            url_change = reverse('admin:cms_genome_browser_coordsystem_changelist')
            url_addnew = reverse('admin:cms_genome_browser_coordsystem_add')
            menu.add_sideframe_item('Edit Coordinate Systems', url=url_change)
            menu.add_modal_item('Add New Coordinate System', url=url_addnew)

        return super(BrowserListView, self).render_to_response(context, **response_kwargs)


class BrowserDetailView(DetailView):
    model = Browser
    template_name = 'cms_genome_browser/browser_detail.html'
    context_object_name = 'browser'

    def render_to_response(self, context, **response_kwargs):
        # Shim to affect the CMS Toolbar only
        if self.request.toolbar:

            menu = self.request.toolbar.get_or_create_menu('genome-browsers-detail-menu', self.object.name)

            url_change = reverse('admin:cms_genome_browser_browser_change', args=[self.object.id])
            url_delete = reverse('admin:cms_genome_browser_browser_delete', args=[self.object.id])
            menu.add_modal_item('Edit %s' % self.object.name, url=url_change)
            menu.add_modal_item('Delete %s' % self.object.name, url=url_delete)
            menu.add_break()

            url_change = reverse('admin:cms_genome_browser_browser_changelist')
            url_addnew = reverse('admin:cms_genome_browser_browser_add')
            menu.add_sideframe_item('Edit Genome Browsers', url=url_change)
            menu.add_modal_item('Add New Genome Browser', url=url_addnew)

        return super(BrowserDetailView, self).render_to_response(context, **response_kwargs)

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/_browser_info.html
<div class="genome-browser-info">
  <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#{{ browser.slug }}-info"><span class="glyphicon glyphicon-info-sign"></span></button>
</div>

<div class="modal fade" id="{{ browser.slug }}-info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About: {{ browser.name }}</h4>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          {{ browser.description|linebreaks }}
        </div>
      </div>

      <div class="modal-footer hidden-xs">
        <div class="btn-group" role="group" aria-label="...">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

      <div class="modal-footer visible-xs">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="btn-group-vertical col-xs-12" role="group" aria-label="...">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/_browser_list_item.html
{% load sekizai_tags staticfiles thumbnail %}

{% addtoblock "css" strip %}
  <link rel="stylesheet" type="text/css" href="{% static 'cms_genome_browser/app.css' %}">
{% endaddtoblock %}

<a class="thumbnail" href="{% url 'cms_genome_browser:browser_detail' browser.slug %}">

  {% if browser.image %}
    <img class="genome-browser-image" src="{% thumbnail browser.image 600x500 crop upscale subject_location=browser.image.subject_location %}" alt="{{ browser.name }}">
  {% else %}
    <img src="http://placehold.it/600x500">
  {% endif %}

  <div class="caption" >
    <h4 class="group inner list-group-item-heading text-center">
      {{ browser.name }}
    </h4>
  </div>

</a>

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/_browser_script.html
<script language="javascript">

  new Browser({
    chr:       '{{ browser.chr }}',
    viewStart: {{ browser.start }},
    viewEnd:   {{ browser.end }},
    cookieKey: 'genome-browser-{{ browser.id }}-{{ browser.slug }}',
    pageName:  'genome-browser-{{ browser.id }}-{{ browser.slug }}',

    fullScreen: true,
    reverseScrolling: true,

    coordSystem: {
      speciesName: '{{ browser.coordinate_system.species.name }}',

      {% if browser.coordinate_system.species.taxid %}
        taxon: {{ browser.coordinate_system.species.taxid }},
      {% endif %}

      auth: '{{ browser.coordinate_system.auth|default:" " }}',

      {% if browser.coordinate_system.version %}
        version: '{{ browser.coordinate_system.version }}',
      {% endif %}

      {% if browser.coordinate_system.ucsc_name %}
        ucscName: '{{ browser.coordinate_system.ucsc_name }}',
      {% endif %}
    },

    sources: [
      {% for track in browser.track_set.all %}
        {% if track.publish_track %}
          {% include "cms_genome_browser/_track.html" %}
        {% endif %}
      {% endfor %}
    ]

  });

</script>

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/_track.html
{
  name: '{{ track.name }}',

  {% if track.description %}
    desc: '{{ track.description }}',
  {% endif %}

  {{ track.uri_label }}: '{{ track.data_file.url }}',

  {% if track.index_file %}
    {% if track.tier_type == 'tabix' %}
      indexURI: '{{ track.index_file.url }}',
    {% else %}
      baiURI: '{{ track.index_file.url }}',
    {% endif %}
  {% endif %}

  {% if track.stylesheet %}
    stylesheet_uri: '{{ track.stylesheet.style_file.url }}',
  {% endif %}

  {% if track.tier_type %}
    tier_type: '{{ track.tier_type }}',
  {% endif %}

  {% if track.payload %}
    payload: '{{ track.payload }}',
  {% endif %}

  {% if track.collapse_super_groups %}
    collapseSuperGroups: true,
  {% endif %}

  {% if track.provides_entrypoint %}
    provides_entrypoints: true,
  {% endif %}

  {% if track.pinned %}
    pinned: true,
  {% endif %}
},

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/browser_detail.html
{% extends "base.html" %}
{% load sekizai_tags staticfiles %}

{% block title %}
  {{ browser.name }}{% if LAB_NAME %} | {{ LAB_NAME }}{% endif %}
{% endblock title %}

{% block content %}

  {% addtoblock "css" strip %}
    <link rel="stylesheet" type="text/css" href="{% static 'cms_genome_browser/app.css' %}">
  {% endaddtoblock %}

  <div class="genome-browser">

    {% include "cms_genome_browser/_browser_info.html" %}

    <script language="javascript" src="http://www.biodalliance.org/release-0.13/dalliance-compiled.js"></script>

    {% include "cms_genome_browser/_browser_script.html" %}

    <div class="container-fluid genome-browser-holder" id="genome-browser-{{ browser.id }}-{{ browser.slug }}"></div>

  </div>

{% endblock content %}

cms_genome_browser/djangocms-genome-browser-0.1.1/cms_genome_browser/templates/cms_genome_browser/browser_list.html
{% extends "base.html" %}
{% load sekizai_tags staticfiles thumbnail %}

{% block content %}

  <div class="container">
    <h1 class="text-center gallery-heading">Genome Browsers</h1>
    <div class="container-fluid">
      <div id="genome-browsers" class="row">
        {% for browser in browser_list %}
          <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
            <div class="item">
              {% include "cms_genome_browser/_browser_info.html" %}
              {% include "cms_genome_browser/_browser_list_item.html" %}
            </div>
          </div>
        {% empty %}
          <p>Need to add genome browsers!</p>
        {% endfor %}
      </div>
    </div>
  </div>

  {% addtoblock "js" strip %}
    <script src="{% static 'cms_genome_browser/jquery.matchHeight-min.js' %}"></script>
    <script src="{% static 'cms_genome_browser/app.js' %}"></script>
  {% endaddtoblock %}

{% endblock content %}